### ISSUE TITLE
Crash report seems to come from VMP (Index -1 out of bounds for length 8193

### ISSUE THREAD

**Issue by Anmegum** [RelativityMC/VMP-fabric#47]
**Describe the bug**
The server starts backing up with mod "Textile backup", shortly after it crashes and the crashlog includes only a reference to VMP in the stacktrace.

**To Reproduce**
1. install Textile Backup
2. Wait a few backup cycles (it doesnt always crash on the same backup attemp)

**Expected behavior**
The backup running through smoothly as it does all of the other times without getting a crash.

**Screenshots**
-none-

**Runtime info (please complete the following information):**
 - OS: Linux (amd64) version 5.15.74-1-pve
 - Minecraft version: 1.20.1
 - Mod version: Very Many Players 0.2.0+beta.7.96
 - Mod branch: (fill this if you are not using the default `ver` branches)

**Crash reports / logs**
Crash-report: https://mclo.gs/hNdrhqL

**Other mods**

**Checklist**

 - [x ] I am using the official version of the mod. 
 - [ ] I tried the latest development version but the issue persists. 
 - [x ] I searched for similar open issues and could not find an existing bug report on this. 

**Additional context**

**Comment by ishland** [comment]
This issue is likely related to Szum123321/textile_backup#123. 

Textile backup appears to be saving worlds asynchronously, which might have caused this issue: 
https://github.com/Szum123321/textile_backup/blob/04533f89fdd4d615f90932f86d46b698339d8f2d/src/main/java/net/szum123321/textile_backup/core/create/ExecutableBackup.java#L69

Changes have been made to prevent asynchronous access to ticket level propagator.
